In [1]:
import numpy as np

## 1. creaet ndarray

### 1.1 list to array

In [2]:
a = np.array([1, 2, 3])
print(type(a), a.shape, a.dtype, a.ndim, a, sep='\n')

<class 'numpy.ndarray'>
(3,)
int32
1
[1 2 3]


In [3]:
b = np.array([(1, 2, 3),(4, 5, 6)], dtype=float)
print(type(b), b.shape, b.dtype, b.ndim, b, sep='\n')

<class 'numpy.ndarray'>
(2, 3)
float64
2
[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
c = np.array([[(1.5, 2, 3), (4, 5.2, 6)], [(3, 2.8, 1),(4, -5.1, 6)]], dtype=int)
print(type(c), c.shape, c.dtype, c.ndim, c, sep='\n')

<class 'numpy.ndarray'>
(2, 2, 3)
int32
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 3  2  1]
  [ 4 -5  6]]]


In [5]:
myList = [1.6, 2, -3.5, 4]
myArray = np.asarray(myList)
myArray

array([ 1.6,  2. , -3.5,  4. ])

#### np.asarray(param)与np.array(param)的区别

In [6]:
# param是列表, 都是复制一个数组
myList = [1, 2, 3, 4]
myArray1 = np.array(myList)
myArray2 = np.asarray(myList)
myList[1] = 1111
print(myArray1, myArray2)

[1 2 3 4] [1 2 3 4]


In [7]:
# param本身就是数组时, np.array()不复制, np.asarray()仍会复制
myArray = np.arange(4)
myArray1 = np.array(myArray)
myArray2 = np.asarray(myArray)
myArray[1] = 1111
print(myArray1, myArray2)

[0 1 2 3] [   0 1111    2    3]


### 1.1+ array to list

In [8]:
a = np.array([1, 2, 3])
aList = a.tolist()
print(type(aList), aList, sep='\n')

<class 'list'>
[1, 2, 3]


### 1.2 arange
arange 的参数可以是float

In [9]:
d = np.arange(1, 5)
print(type(d), d.shape, d.dtype, d.ndim, d, sep='\n')

<class 'numpy.ndarray'>
(4,)
int32
1
[1 2 3 4]


In [10]:
np.arange(4.3, 6, 0.5) 

array([4.3, 4.8, 5.3, 5.8])

### python内置函数range()的start, end, step都不可以是float

### 1.3 linspace() 等差数列

In [11]:
e= np.linspace(0, 2, 3) # 默认包括终止值， 分两份
print(type(e), e.shape, e.dtype, e.ndim, e, sep='\n')

<class 'numpy.ndarray'>
(3,)
float64
1
[0. 1. 2.]


In [12]:
e= np.linspace(0, 2, 3, endpoint=False) # 不包括终止值， 分三份
print(type(e), e.shape, e.dtype, e.ndim, e, sep='\n')

<class 'numpy.ndarray'>
(3,)
float64
1
[0.         0.66666667 1.33333333]


### 1.3+ logspace() 创建等比数列

In [13]:
# 创建起始值为10^1，终止值为10^2，有4个数的等比数列
np.logspace(1, 2, 4)

array([ 10.        ,  21.5443469 ,  46.41588834, 100.        ])

In [14]:
# 创建起始值为2^0，终止值为2^5(不包括)，有4个数的等比数列
np.logspace(0, 5, 4, endpoint=False, base=2)

array([ 1.        ,  2.37841423,  5.65685425, 13.45434264])

In [15]:
13.45434264 * 2.37841423

31.99999999027177

### 1.4 np.ones(shape, dtype=None, order='C') 必须有参数,第一个表示形状,是整数或整数序列

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

### 1.5 np.full(shape, fill_value, dtype=None, order='C') 至少需要两个参数

In [19]:
np.full(4, 3.4)

array([3.4, 3.4, 3.4, 3.4])

In [20]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

### 1.6 np.zeros(shape, dtype=float, order='C')

In [21]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.zeros(3, dtype=int)

array([0, 0, 0])

### 1.7 np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
### identity(n, dtype=None)

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(2, 5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [25]:
np.eye(4, k=2)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 1.8 np.random.random 

In [27]:
help(np.random.random)

Help on built-in function random_sample:

random_sample(...) method of mtrand.RandomState instance
    random_sample(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0).
    
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` multiply
    the output of `random_sample` by `(b-a)` and add `a`::
    
      (b - a) * random_sample() + a
    
    Parameters
    ----------
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    
    Returns
    -------
    out : float or ndarray of floats
        Array of random floats of shape `size` (unless ``size=None``, in which
        case a single float is returned).
    
    Examples
    --------
    >>> np.random.random_sample()
    0.47108547995356098
    >>> type(np.random.random_

In [28]:
np.random.random((2, 3)) # [0.0, 1.0) 随机分布

array([[0.88759518, 0.97596816, 0.7198916 ],
       [0.40662172, 0.66780236, 0.25527677]])

In [29]:
np.random.random(4) # [0.0, 1.0) 随机分布

array([0.45718808, 0.62847757, 0.29233623, 0.40080667])

### 1.8+ np.random.rand() 

In [30]:
np.random.rand(2, 4)  # [0, 1)均匀分布的样本

array([[0.72505123, 0.17887854, 0.96576901, 0.35895107],
       [0.71381363, 0.59997734, 0.74343203, 0.02072276]])

In [31]:
np.random.rand(3)

array([0.58986693, 0.04380098, 0.0204235 ])

### 1.8++ np.random.normal() 

In [32]:
np.random.normal(size=(2, 3)) # 标准正态分布样本

array([[-0.244288  ,  1.04116271,  0.59497442],
       [ 0.99432477,  0.78634288,  1.10747654]])

### 1.9 np.empty

In [33]:
# 根据指定的形状创建,并不是0 只是未初始化的垃圾数据
np.empty((3, 2))

array([[0.244288  , 1.04116271],
       [0.59497442, 0.99432477],
       [0.78634288, 1.10747654]])

In [34]:
np.empty(3)

array([0.58986693, 0.04380098, 0.0204235 ])

### 1.10 np.ones_like()  np.zeros_like()  np.empty_like()  
#### 参数是array-like, 生成和参数形状一样

In [35]:
e = np.array([[2, 4, 1],[5, 6, 5]])

In [36]:
np.ones_like(e)

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
np.zeros_like(e)

array([[0, 0, 0],
       [0, 0, 0]])

In [38]:
np.empty_like(e)

array([[-1645331856,  1071833136,  -151241312],
       [ 1067871508,   -48854816,  1066723813]])