In [1]:
import numpy as np

## 线性代数

In [2]:
x = np.arange(6).reshape(2, 3)
print(x)

y = np.arange(2, 8).reshape(3, 2)
y

[[0 1 2]
 [3 4 5]]


array([[2, 3],
       [4, 5],
       [6, 7]])

###  np.dot() 矩阵相乘

In [3]:
np.dot(x, y)

array([[16, 19],
       [52, 64]])

In [4]:
y = np.array([[1], [1], [1]])
print(y, '\n')

np.dot(x, y)

[[1]
 [1]
 [1]] 



array([[ 3],
       [12]])

### 注意下面情况: 这里形状不匹配 也可以相乘

In [5]:
y = np.ones(3)
print(y)
np.dot(x, y)

[1. 1. 1.]


array([ 3., 12.])

In [6]:
from numpy import linalg # algebra 翻译为: 代数

### np.diag() 
#### 1 取出方阵的对角线元素并返回一维数组
#### 2 将一维数组转换成方阵,其他元素用0填充

In [7]:
mat3 = np.array([[3, 2, 3], [4, 5, 6],[7, 8, 9]])
np.diag(mat3)

array([3, 5, 9])

In [8]:
np.diag([1, 2, 3, 4, 5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### np.trace() 方阵的迹

In [9]:
np.trace(mat3)

17

### linalg.det() 行列式

In [10]:
linalg.det(mat3)

-6.0000000000000036

### linalg.pinv(mat3)  矩阵的伪逆 ,如果矩阵可逆,那么伪逆矩阵与逆矩阵相同

In [11]:
linalg.pinv(mat3) 

array([[ 0.5       , -1.        ,  0.5       ],
       [-1.        , -1.        ,  1.        ],
       [ 0.5       ,  1.66666667, -1.16666667]])

### linalg.inv(mat3)  矩阵的逆 ,如果矩阵不可逆, 会报错

In [12]:
linalg.inv(mat3)

array([[ 0.5       , -1.        ,  0.5       ],
       [-1.        , -1.        ,  1.        ],
       [ 0.5       ,  1.66666667, -1.16666667]])

In [13]:
mat = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print("行列式:", linalg.det(mat))
try:
    linalg.inv(mat)
except Exception as e:
    print("错误信息:", e, ", 翻译为: 奇异矩阵")

行列式: 0.0
错误信息: Singular matrix , 翻译为: 奇异矩阵


In [14]:
mat3

array([[3, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### linalg.qr() QR分解

In [15]:
q, r = linalg.qr(mat3)
print(q, r, sep='\n\n')

[[-0.34874292  0.90632023 -0.23866719]
 [-0.46499055 -0.38842295 -0.79555728]
 [-0.81373347 -0.16646698  0.5568901 ]]

[[ -8.60232527  -9.53230638 -11.15977332]
 [  0.          -1.46121016  -1.10977987]
 [  0.           0.          -0.47733437]]


### linalg.eig() 求特征值和特征向量
#### 这里需要注意的是,输入的矩阵需要是方阵

In [16]:
mat = np.array([[-1, 1, 0],
                [-4, 3, 0],
                [1, 0, 2]])
a, b = linalg.eig(mat)
print("特征值a:", a)
print("\n特征向量b:\n", b)
# a第一个特征值对应的是b的第一列

特征值a: [2. 1. 1.]

特征向量b:
 [[ 0.          0.40824829  0.40824829]
 [ 0.          0.81649658  0.81649658]
 [ 1.         -0.40824829 -0.40824829]]


### linalg.svd()  奇异值分解
#### 输入的可以不是方阵, 求得的是输入矩阵的奇异值而不是特征值

In [17]:
mat = np.array([[1, 1],
                [1, 1],
                [0, 0]])
a, b, c = linalg.svd(mat)
print(a, b, c, sep='\n\n')

[[-0.70710678 -0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]

[2. 0.]

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
