In [1]:
import numpy as np

##  属性

In [2]:
d1d = np.array([1, 2, 3])
d2d = np.array([[1.8, 2, 3, 2.4], [3, 4, 5, 8]])

#### ndarray.ndim	秩，即轴的数量或维度的数量

In [3]:
print(d1d.ndim)
print(d2d.ndim)

1
2


#### ndarray.shape	数组的维度，对于矩阵，n 行 m 列

In [4]:
print(d1d.shape)
print(d2d.shape)

(3,)
(2, 4)


#### ndarray.size	数组元素的总个数，相当于 .shape 中 n*m 的值

In [5]:
print(d1d.size)
print(d2d.size)

3
8


#### ndarray.dtype	对象的元素类型

In [6]:
print(d1d.dtype)
print(d2d.dtype)

int32
float64


#### ndarray.itemsize	对象中每个元素的大小，以字节为单位

In [7]:
print(d1d.itemsize) # int32-->4字节
print(d2d.itemsize) # float64-->8字节

4
8


#### ndarray.flags	对象的内存信息

In [8]:
print(d1d.flags, '\n')
print(d2d.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False 

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


#### ndarray.real  元素的实部

In [9]:
d1d = np.array([1 + 2j, 3.7 + 3j])
d2d = np.array([[1 + 2j, 3.7 + 3j], [4.5, 8 - 4.8j]])

print(d1d.real)
d2d.real

[1.  3.7]


array([[1. , 3.7],
       [4.5, 8. ]])

#### ndarray.imag	 元素的虚部

In [10]:
print(d1d.imag)
d2d.imag

[2. 3.]


array([[ 2. ,  3. ],
       [ 0. , -4.8]])

#### ndarray.data	包含实际数组元素的缓冲区，由于一般通过数组的索引获取元素，所以通常不需要使用这个属性

In [11]:
print(d1d.data)
d2d.data

In [12]:
del d1d, d2d

## ================================

In [13]:
c = np.array([[1.8, 2, 3, 2.4], [3, 4, 5, 8]], dtype=float)
# 修改形状  并不是转置， 相当于 转为一维数组再重新排列， 
c.shape = (4, -1)  # -1就是根据4进行确定
c

array([[1.8, 2. ],
       [3. , 2.4],
       [3. , 4. ],
       [5. , 8. ]])

In [14]:
# 可以通过reshape（）方法进行重造，只是这样是新创建数组，虽然此时和d是不同的对象，
# 其id值也不同，但是其内部存储的数据确实相同的，改变c中某个数据，
# d中对应的数据也会随之变化。
d = c.reshape(2, 4) 
print(c, '\n\n', d)

[[1.8 2. ]
 [3.  2.4]
 [3.  4. ]
 [5.  8. ]] 

 [[1.8 2.  3.  2.4]
 [3.  4.  5.  8. ]]


In [15]:
c[3, 0] = 666
print(c, '\n\n', d)

[[  1.8   2. ]
 [  3.    2.4]
 [  3.    4. ]
 [666.    8. ]] 

 [[  1.8   2.    3.    2.4]
 [  3.    4.  666.    8. ]]


In [16]:
# 转化元素类型
c2 = c.astype(int) # 创建一个新数组， c本身的类型不会改变
print(c2)
print(c2.dtype)

[[  1   2]
 [  3   2]
 [  3   4]
 [666   8]]
int32


In [17]:
# c本身的类型不会改变
c

array([[  1.8,   2. ],
       [  3. ,   2.4],
       [  3. ,   4. ],
       [666. ,   8. ]])