In [2]:
import numpy as np

#  通用函数(元素级别)

In [7]:
x = np.array([[2.7, -4.8, 3.2], 
              [0.2, 1, -3.2]])
x

array([[ 2.7, -4.8,  3.2],
       [ 0.2,  1. , -3.2]])

In [8]:
np.abs(x)

array([[2.7, 4.8, 3.2],
       [0.2, 1. , 3.2]])

In [9]:
np.fabs(x)

array([[2.7, 4.8, 3.2],
       [0.2, 1. , 3.2]])

In [10]:
# abs()和fabs()区别是: fabs()不能求虚数的绝对值,如果是普通纸会更快
print(np.abs(3 + 4j))

5.0


In [11]:
try:
    np.fabs(2 - 4j)
except TypeError as e:
    print("异常信息:", e)


异常信息: ufunc 'fabs' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''


In [12]:
np.exp(x)

array([[1.48797317e+01, 8.22974705e-03, 2.45325302e+01],
       [1.22140276e+00, 2.71828183e+00, 4.07622040e-02]])

In [13]:
y = np.fabs(x)
print("默认底数是自然对数的底:\n", np.log(y))
print("\n底为10:\n", np.log10(y))
print("\n底为2:\n", np.log2(y))

默认底数是自然对数的底:
 [[ 0.99325177  1.56861592  1.16315081]
 [-1.60943791  0.          1.16315081]]

底为10:
 [[ 0.43136376  0.68124124  0.50514998]
 [-0.69897     0.          0.50514998]]

底为2:
 [[ 1.43295941  2.26303441  1.67807191]
 [-2.32192809  0.          1.67807191]]


In [14]:
x

array([[ 2.7, -4.8,  3.2],
       [ 0.2,  1. , -3.2]])

In [15]:
np.sign(x) 

array([[ 1., -1.,  1.],
       [ 1.,  1., -1.]])

In [16]:
np.ceil(x)

array([[ 3., -4.,  4.],
       [ 1.,  1., -3.]])

In [17]:
np.floor(x)

array([[ 2., -5.,  3.],
       [ 0.,  1., -4.]])

In [18]:
np.rint(x) # 去最近的整数

array([[ 3., -5.,  3.],
       [ 0.,  1., -3.]])

In [19]:
res = np.modf(x) # 得到的是元组
print("整数部分:\n", res[0])
print("\n小数部分:\n", res[1])

整数部分:
 [[ 0.7 -0.8  0.2]
 [ 0.2  0.  -0.2]]

小数部分:
 [[ 2. -4.  3.]
 [ 0.  1. -3.]]


In [20]:
np.sqrt(np.fabs(x))

array([[1.64316767, 2.19089023, 1.78885438],
       [0.4472136 , 1.        , 1.78885438]])

In [21]:
a = np.array([[2.7, np.nan, 3.2], 
              [0.2, 1, np.nan]])
np.isnan(a)

array([[False,  True, False],
       [False, False,  True]])

In [22]:
x = np.random.randn(6)
y = np.random.randn(6)
print("x:", x)
print("y:", y)
np.maximum(x, y) # 取大值

x: [-0.82816772 -1.22535141  1.36721368  0.20323174 -0.24618571 -0.07057591]
y: [-1.73218975  0.96139149 -0.26147458 -0.00375204  1.96819147 -1.25419755]


array([-0.82816772,  0.96139149,  1.36721368,  0.20323174,  1.96819147,
       -0.07057591])