In [1]:
import numpy as np

# 5 数学和统计方法

In [2]:
arr = np.array([[1, 4, 3, 2], [2, 3, 1, 0]])
arr

array([[1, 4, 3, 2],
       [2, 3, 1, 0]])

In [3]:
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))
print(np.sum(arr))

[3 7 4 2]
[10  6]
16


In [4]:
print(np.max(arr, axis=0))
print(np.max(arr, axis=1))
print(np.max(arr))

[2 4 3 2]
[4 3]
4


In [5]:
print(np.argmax(arr, axis=0))
print(np.argmax(arr, axis=1))
print(np.argmax(arr))

[1 0 0 0]
[1 1]
1


In [6]:
print(np.cumsum(arr, axis=0))
print()
print(np.cumsum(arr, axis=1))
print()
print(np.cumsum(arr))

[[1 4 3 2]
 [3 7 4 2]]

[[ 1  5  8 10]
 [ 2  5  6  6]]

[ 1  5  8 10 12 15 16 16]


In [7]:
print(np.cumprod(arr, axis=0))
print()
print(np.cumprod(arr, axis=1))
print()
print(np.cumprod(arr))

[[ 1  4  3  2]
 [ 2 12  3  0]]

[[ 1  4 12 24]
 [ 2  6  6  0]]

[  1   4  12  24  48 144 144   0]


#  6 布尔数组的方法

In [8]:
arr = np.random.randn(6)
arr

array([ 0.37890407,  1.38591522, -0.18999709,  0.0211365 ,  0.29948274,
        1.07861187])

In [9]:
# 大于某数的数量
(arr > 0.5).sum()

2

In [10]:
bools = np.array([False, False, True, False])
print(bools.any()) # 是不是有 True
print(bools.all()) # 是不是全是 True

True
False


# 7 排序

In [11]:
arr = np.array([3, 4, -3, 2])
arr

array([ 3,  4, -3,  2])

In [12]:
arr.sort() # 直接修改本身， 无返回值
arr

array([-3,  2,  3,  4])

In [13]:
arr = np.array([3, 4, -3, 2])
print("原始数组:", arr)
res = np.sort(arr) # 返回新数组，本身也变
print("返回的结果:", res)
print("原始数组:", arr)

原始数组: [ 3  4 -3  2]
返回的结果: [-3  2  3  4]
原始数组: [ 3  4 -3  2]


如果是多维数组，还可以按axis来指定 排序：

In [14]:
arr = np.array([[3, 4, 2], [4, 2, 9], [1, 6, 0]])
print(arr)
arr0 = arr.copy()
arr1 = arr.copy()

[[3 4 2]
 [4 2 9]
 [1 6 0]]


In [15]:
arr0.sort(axis=0) # 每 列 排序 此处不能写‘index’
print(arr0)

[[1 2 0]
 [3 4 2]
 [4 6 9]]


In [16]:
arr1.sort(axis=1) # 每 行 排序  此处不能写‘columns’
print(arr1)

[[2 3 4]
 [2 4 9]
 [0 1 6]]


# 8 单一性和其他集合逻辑
###  np.unique(array)去重 排序

In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [18]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [19]:
# 二维数组
c = np.array([[1, 2], 
              [3, 4], 
              [1, 2], 
              [7, 6]])
np.unique(c) # 超出你的想象

array([1, 2, 3, 4, 6, 7])

In [20]:
np.array(list(set([tuple(t) for t in c])))

array([[1, 2],
       [7, 6],
       [3, 4]])

### np.in1d() 测试一个数组的值是否在另一个数组里，返回一个布尔数组

In [21]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

### np.concatenate() 拼接

In [22]:
# 一维数组的拼接
a = np.arange(1, 10)
b = np.arange(20, 25)
np.concatenate((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 21, 22, 23, 24])

In [23]:
# 二维数组的拼接
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(21, 25).reshape(2, 2)

In [24]:
# 行下加行
np.concatenate((a, b)) # === np.concatenate((a, b), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [21, 22],
       [23, 24]])

In [25]:
# 列后加列
np.concatenate((a, b), axis=1)

array([[ 1,  2, 21, 22],
       [ 3,  4, 23, 24]])

### np.stack() 交叉合并数组

In [26]:
a = np.arange(1, 10).reshape((3, 3))
b = np.arange(11, 20).reshape((3, 3))
c = np.arange(101, 110).reshape((3, 3))

In [27]:
np.stack((a, b, c), axis=0) # 每个二维数组后插入一个二维数组

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  12,  13],
        [ 14,  15,  16],
        [ 17,  18,  19]],

       [[101, 102, 103],
        [104, 105, 106],
        [107, 108, 109]]])

In [28]:
np.stack((a, b, c), axis=1) # 每一行后插入另一个二维数组的一行

array([[[  1,   2,   3],
        [ 11,  12,  13],
        [101, 102, 103]],

       [[  4,   5,   6],
        [ 14,  15,  16],
        [104, 105, 106]],

       [[  7,   8,   9],
        [ 17,  18,  19],
        [107, 108, 109]]])

In [29]:
np.stack((a, b, c), axis=2) # 每一列插入二维数组的一列 

array([[[  1,  11, 101],
        [  2,  12, 102],
        [  3,  13, 103]],

       [[  4,  14, 104],
        [  5,  15, 105],
        [  6,  16, 106]],

       [[  7,  17, 107],
        [  8,  18, 108],
        [  9,  19, 109]]])

### np.vstack() 交叉合并数组,只接受一个元祖类型的参数, (不增加维度)

In [33]:
np.vstack((a, b, c))

array([[  1,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 11,  12,  13],
       [ 14,  15,  16],
       [ 17,  18,  19],
       [101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [35]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])