In [1]:
import numpy as np

## I/O
save loading

### 以二进制形式存储

In [2]:
# 存一个数组,且未压缩
x = np.arange(10)
np.save("myfile", x) # 如果不是".npy"的扩展名,则自动加上扩展名".npy"

y = np.load("myfile.npy")
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 多个数组压缩存储到文件中
x = np.arange(10)
y = np.arange(20, 30, 2)
np.savez("myfile2.npz", x=x, y=y)

data= np.load("myfile2.npz")
print(data['x'])
print(data['y'])

[0 1 2 3 4 5 6 7 8 9]
[20 22 24 26 28]


### 以文本形式存储

In [4]:
!type array.txt

1, 2, 3, 4, 5
2, 3, 4, 5, 6
3, 4, 5, 6, 7
4, 5, 6, 7, 8


In [5]:
arr = np.loadtxt("array.txt", delimiter=",")
print(arr)

[[1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


In [6]:
np.savetxt("array2.txt", arr, delimiter="|||")