# reshape 修改形状并返回,但是并不是复制

In [23]:
import numpy as np
 
a = np.arange(6).reshape(2, 3)
print ('原始数组：')
print (a)
print ('\n')
 
b = a.reshape(-1) # 原始数租形状并不变
print ('变形后的数组：')
print (b)

原始数组：
[[0 1 2]
 [3 4 5]]


变形后的数组：
[0 1 2 3 4 5]


In [24]:
# 但是具体数据是一致的,一个变,另一个也变
b[2] = 222
print("B: \n", b)
print("\na也会改变:\n", a)

B: 
 [  0   1 222   3   4   5]

a也会改变:
 [[  0   1 222]
 [  3   4   5]]


In [25]:
del a, b

# flatten 拉成一维数据,返回一份数组拷贝，对拷贝所做的修改不会影响原始数组

In [26]:
import numpy as np
 
a = np.arange(6).reshape(2, 3)
print ('原始数组a：')
print (a)
print ('\n')
 
b = a.flatten() 
print ('拉平后的数组b：')
print (b)

原始数组a：
[[0 1 2]
 [3 4 5]]


拉平后的数组b：
[0 1 2 3 4 5]


In [5]:
# 改变其中一个的数值,另一个也不变
b[2] = 222
print("B: ", b)
print("a不不不变:\n", a)

B:  [  0   1 222   3   4   5]
a不不不变:
 [[0 1 2]
 [3 4 5]]


In [6]:
del a, b

# ravel 拉成一维数据并返回,但并不是拷贝

In [27]:
a = np.arange(6).reshape(2, 3)
print ('原始数组a：')
print (a)
print ('\n')
 
b = a.ravel() # # 原始数组a形状并不变
print ('拉平后的数组b：')
print (b)

原始数组a：
[[0 1 2]
 [3 4 5]]


拉平后的数组b：
[0 1 2 3 4 5]


In [8]:
# 改变其中一个的数值,另一个也变
b[2] = 222
print("B: ", b)
print("a也会改变:\n", a)

B:  [  0   1 222   3   4   5]
a也会改变:
 [[  0   1 222]
 [  3   4   5]]


# squeeze()只能将包含一个数字的多维数组拉平为一维并返回, 但并不是复制

In [9]:
a = np.array([[0], [1], [2], [3], [4], [5]])
print ('原始数组a：')
print (a)
 
b = a.squeeze() # 原始数组a并不变
print ('拉平后的数组b：')
print (b)
print()

# 改变其中一个的数值,另一个也变
b[2] = 222
print("B: ", b)
print("a也会改变:\n", a)

原始数组a：
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
拉平后的数组b：
[0 1 2 3 4 5]

B:  [  0   1 222   3   4   5]
a也会改变:
 [[  0]
 [  1]
 [222]
 [  3]
 [  4]
 [  5]]


In [10]:
a = np.arange(6).reshape(2, 3)
print ('原始数组a：')
print (a)
print ('\n')
 
b = a.squeeze()
print ('无法拉平为一维数组')
print (b)

原始数组a：
[[0 1 2]
 [3 4 5]]


无法拉平为一维数组
[[0 1 2]
 [3 4 5]]


In [11]:
del a, b

# flat 是一个数组元素迭代器

In [12]:
a = np.arange(9).reshape(3, 3)
type(a.flat)

numpy.flatiter

In [13]:
for element in a.flat:
    print("one element:", element)

one element: 0
one element: 1
one element: 2
one element: 3
one element: 4
one element: 5
one element: 6
one element: 7
one element: 8


In [14]:
del a