In [1]:
import numpy as np

In [2]:
d = np.array([(1, 2, 1), (2, 3, 2)])
d

array([[1, 2, 1],
       [2, 3, 2]])

In [3]:
d + d

array([[2, 4, 2],
       [4, 6, 4]])

In [4]:
d * d # *左右形状不同，会报错

array([[1, 4, 1],
       [4, 9, 4]])

In [5]:
### 不同形状的运算叫做广播 

In [6]:
d * 2

array([[2, 4, 2],
       [4, 6, 4]])

In [7]:
1 / d

array([[1.        , 0.5       , 1.        ],
       [0.5       , 0.33333333, 0.5       ]])

In [8]:
d ** 2

array([[1, 4, 1],
       [4, 9, 4]], dtype=int32)

In [9]:
a = np.arange(0, 60, 10).reshape(-1, 1)
a

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [10]:
b = np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [11]:
a + b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [13]:
x = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
x = np.tile(x, (5, 1))
x

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])